title: Sevester # your name (or website title) here
logo: ("/images/sevester-1.jpg"){:height="250px" width="180px"} # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My Name is Sevester, and my portfolio is a representation of all that I've learned and accomplished as a science data students.
  <br>The writing samples in this portfolio shows the skills I have developed over the course of the program.
  <br>I have some experience as Associate Data Analyst in NTUC LearningHub. 
  <br>I have worked on several project using: Python, SQL, PowerBI, and Excel to generate reports and insights. 
  <br>
  <a href="https://www.linkedin.com/in/sevesters/">View My LinkedIn Profile</a> 
  <br>
  <br>
  <br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
